#!/usr/bin/env python3.9
from bs4 import BeautifulSoup
import requests
import re
from lxml import etree
import argparse
parser = argparse.ArgumentParser()
parser.add_argument('--address' , '-a',help="Select a Wallet Address" , action="store_true")
parser.add_argument("WalletAddress",  nargs='?')

args = parser.parse_args()


if args.address:
    try:
        page_to_load = ("https://www.blockchain.com/btc/address/" + args.WalletAddress)
        page = requests.get("https://www.blockchain.com/btc/address/" + args.WalletAddress)
    except TypeError:
        print('\n Invalid Wallet Adress \n')
        exit()
else:
    print('Invalid Options for help pleace use -h')
    exit()
soup = BeautifulSoup(page.content, 'html.parser')

selector = etree.HTML(str(soup))
print('Transactions = ' + selector.xpath('/html/body/div[1]/div[3]/div/div[2]/div/div[1]/div[2]/div/div[3]/div[2]/span')[0].text)

print('Total Recieved = ' + selector.xpath('/html/body/div[1]/div[3]/div/div[2]/div/div[1]/div[2]/div/div[4]/div[2]/span')[0].text)

print('Total Sent = ' + selector.xpath('/html/body/div[1]/div[3]/div/div[2]/div/div[1]/div[2]/div/div[5]/div[1]/div/span')[0].text)

print('Final Balance = ' + selector.xpath('/html/body/div[1]/div[3]/div/div[2]/div/div[1]/div[2]/div/div[6]/div[2]/span')[0].text)

print('Hash Type = ' + selector.xpath('/html/body/div[1]/div[3]/div/div[2]/div/div[1]/div[2]/div/div[2]/div[2]/span')[0].text)

print(f'All Scraped From {page_to_load}')




